package com.serenegiant.myhome.bean;

import java.util.Map;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.AbstractDaoSession;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.identityscope.IdentityScopeType;
import org.greenrobot.greendao.internal.DaoConfig;

import com.serenegiant.myhome.bean.FoodBean;

import com.serenegiant.myhome.bean.FoodBeanDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see org.greenrobot.greendao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig foodBeanDaoConfig;

    private final FoodBeanDao foodBeanDao;

    public DaoSession(Database db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        foodBeanDaoConfig = daoConfigMap.get(FoodBeanDao.class).clone();
        foodBeanDaoConfig.initIdentityScope(type);

        foodBeanDao = new FoodBeanDao(foodBeanDaoConfig, this);

        registerDao(FoodBean.class, foodBeanDao);
    }
    
    public void clear() {
        foodBeanDaoConfig.clearIdentityScope();
    }

    public FoodBeanDao getFoodBeanDao() {
        return foodBeanDao;
    }

}
